CREATE TABLE lending (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_id INT NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    estimated_return TIMESTAMP NOT NULL,
    time_of_return TIMESTAMP NULL,
    observation VARCHAR(255) NULL,
    employee_id INT NOT NULL,
    tool_id INT NOT NULL,

    CONSTRAINT fk_lending_status
        FOREIGN KEY (status_id)
        REFERENCES lending_status (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_lending_employee
        FOREIGN KEY (employee_id)
        REFERENCES employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_lending_tool
        FOREIGN KEY (tool_id)
        REFERENCES tool (id)
        ON DELETE RESTRICT
);
