CREATE TABLE lending_status (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lending_status VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO lending_status (lending_status) VALUES
('ATIVO'),
('DEVOLVIDO'),
('ATRASADO'),
('RESERVADO');
